innerr/ticat

- pkg/cli/core/cmd.go
- pkg/cli/core/cmds.go
- pkg/cli/parser/cmd_test.go
- pkg/main/main.go
Usage:
```
When env or args has kv pair:
threads=100;200;300
Then a ​flow:
​    **echo [[*threads*]] : dummy :**
Will be rendered to:
​    echo 100 : dummy :
​    echo 200 : dummy :
​    echo 300 : dummy :
```
Special chars: `;` `[[*` `*]]` `**`
> flow template: support multiply rendering by value list

- pkg/cli/core/cmd.go
- pkg/proto/mod_meta/mod_reg.go
Synx in .ticat/.tiflow:
```
flow = sleep 6s
begin-ts-key = test.begin
end-ts-key = test.end
dur-key = test.secs
```
Executing result:
> .ticat/.tiflow file can define auto-timer now

- pkg/builtin/builtin.go
- pkg/builtin/env.go
- pkg/builtin/flow.go
- pkg/builtin/misc.go
- pkg/builtin/sessions.go
- pkg/builtin/utils.go
- pkg/cli/core/cmds.go
- pkg/cli/core/env_val.go
- pkg/cli/core/flow.go
- pkg/cli/core/session.go
- pkg/cli/display/color.go
- pkg/cli/execute/cmd_type.go
- pkg/cli/execute/executor.go
- pkg/main/main.go
- pkg/utils/misc.go
A execution of ticat command(or flow) called session.
(Running a builtin simple command will not treat as a session, eg: `ticat env.ls`)
`sessions.list` show all executed/ing sessions:
`sessions.last` show the last started session:
`sessions.clean` remove all executed sessions:
> feature cmds: sessions management

- pkg/builtin/builtin.go
- pkg/builtin/dump_cmds.go
- pkg/builtin/sessions.go
- pkg/cli/core/cli.go
- pkg/cli/core/cmd.go
- pkg/cli/core/env.go
- pkg/cli/core/executed.go
- pkg/cli/core/executing.go
- pkg/cli/core/flow.go
- pkg/cli/core/parsing.go
- pkg/cli/core/session.go
- pkg/cli/display/flow.go
- pkg/cli/execute/executor.go
Use `sessions.list <find-str> <find-str> ..` to review all executed commands:
Use `sessions.list.desc <find-str> <find-str> ..` to review the details of one executed command, check the error point:
Similiar usage in `sessions.last` `sessions.last.desc`:
> Feature: use sessions.last.desc to review|check the executed commands

- pkg/builtin/builtin.go
- pkg/builtin/env.go
- pkg/builtin/sessions.go
- pkg/cli/core/cli.go
- pkg/cli/core/cmd.go
- pkg/cli/core/cmds.go
- pkg/cli/core/dep.go
- pkg/cli/core/env.go
- pkg/cli/core/env_ops.go
- pkg/cli/core/executed.go
- pkg/cli/core/executing.go
- pkg/cli/core/session.go
- pkg/cli/display/cmds.go
- pkg/cli/display/executor.go
- pkg/cli/display/flow.go
- pkg/cli/execute/cmd_type.go
- pkg/cli/execute/executor.go
Use `sessions.list <find-str> <find-str> ...` to browse and search executed sessions:
Use `sessions.list.desc id=<session-id>` to check the executed status:
Use `sessions.list.retry id=<session-id>` to retry this session *from error point* (will be a lot faster than executing all).
Use `sessions.list.desc id=<session-id>` to checkout the executed status, the session-id could be the original session or a retry session.
Retry but still failed:
(Fix code and) Retry again, succeeded:
> Feature: session retry supporting

- pkg/cli/core/cmd.go
- pkg/proto/mod_meta/mod_reg.go
Interactive modules (eg: `mysql.login`) could use this feature to correctly function (without executing logs, it's side effect)
Usage in a `*.ticat` or `*.tiflow` file:
```
interactive = true
```
or
```
unlog = true
```
> support interactive definition in *.ticat/*.tiflow

- pkg/builtin/builtin.go
- pkg/builtin/dbg.go
- pkg/builtin/sessions.go
- pkg/cli/core/argv.go
- pkg/cli/core/breakpoints.go
- pkg/cli/core/cli.go
- pkg/cli/core/cmd.go
- pkg/cli/core/cmds.go
- pkg/cli/core/env_val.go
- pkg/cli/core/errs.go
- pkg/cli/core/executed.go
- pkg/cli/core/executing.go
- pkg/cli/core/sys_argv.go
- pkg/cli/core/template.go
- pkg/cli/display/color.go
- pkg/cli/display/err.go
- pkg/cli/display/flow.go
- pkg/cli/display/render.go
- pkg/cli/display/suggest.go
- pkg/cli/execute/executor.go
- pkg/cli/execute/interactive.go
This feature will provide high flexibility to control how we run flows.
And very useful for module development.
Use the command set `dbg.break` to setup break-points, so that we could skip or execute or re-execute specified commands:
An example, use `dbg.break.at` to pause the execution at the command `tidb.deploy`
At the paused status, we could step-in, step-over a command or a subflow:
And use the interactive mode to run any commands under this env:
We expect `dbg.break.at.begin` will be popular:
> Feature: break-points, step in/out/over, interactive mode

- CHANGELOG.md
- pkg/builtin/env.go
- pkg/builtin/hub.go
- pkg/cli/display/help.go
- pkg/cli/display/suggest.go
- pkg/proto/hub_meta/hub_repo.go
Relocate storing path for each git repo.
The existed repos stored in local dirs will stay untouched(could remove by `hub.reset` or `hub.rm`),
`hub.init` or `hub.add` may needed for re-adding the old repos.
> relocate repo's local store dir

- pkg/builtin/blender.go
- pkg/builtin/builtin.go
- pkg/cli/core/blender.go
- pkg/cli/core/cli.go
- pkg/cli/execute/executor.go
> blender.forest-mode: reset env on each command, but not reset on their subflows

- pkg/builtin/env.go
- pkg/builtin/sessions.go
- pkg/cli/core/cmd.go
- pkg/cli/core/template.go
- pkg/proto/meta_file/meta_file.go
- pkg/proto/mod_meta/mod_reg.go
The meta file test-macro.tiflow:
```
help = an example to show how to use macro in meta file
[[prepare]] = noop : echo [[sys.session.id.ip]]
[[run]] = dm : sleep
[[runx]] = [[run]] : [[run]]
flow = [[prepare]] : [[runx]]
```
The flow generated by macros:
> support macro definition in meta file

- CHANGELOG.md
- pkg/builtin/env.go
- pkg/builtin/flow.go
- pkg/builtin/mod.go
- pkg/proto/flow_file/flow_file.go
- pkg/proto/hub_meta/repo.go
- pkg/proto/meta_file/meta_file.go
- pkg/proto/mod_meta/mod_reg.go
Example:
```
help = not use utf8 display by default
abbr = app.disp.utf.disable
flow = display.utf8.off : env.save
help = not use utf8 symbol display by default
abbr = app.disp.utf.sym.off
flow = display.utf8.sym.off : env.save
help = use utf8 symbol display by default
abbr = app.disp.utf.symbols|symbals|symbal|sym
flow = display.utf8.sym : env.save
help = use utf8 display by default
abbr = app.disp.utf
flow = display.utf8 : env.save
```
> support combined format `.tiflow` file

- pkg/cli/core/args_auto_map.go
- pkg/cli/core/cmd.go
- pkg/cli/core/parsing.go
- pkg/cli/execute/executor.go
- pkg/cli/parser/cmd.go
- pkg/cli/parser/cmd_test.go
- pkg/proto/flow_file/flow_file.go
- pkg/proto/meta_file/meta_file.go
- pkg/proto/mod_meta/mod_reg.go
Usage:
Result:
Full mapping with `*`:
Result:
(A lot more args and arg2env)
`flow.save` will use full mapping now.
> support `args.auto` in meta, to auto generate args and arg2env for cmd

- pkg/cli/core/args_auto_map.go
- pkg/cli/core/env_ops.go
Before this improvement:
After: (reduce some args)
So the not necessary args(and keys) could not be exposed to user.
> auto args mapping: not map the keys which already have provides

- pkg/cli/core/args.go
- pkg/cli/core/args_auto_map.go
- pkg/cli/core/cmd.go
- pkg/cli/core/cmds.go
- pkg/cli/core/template.go
- pkg/cli/display/cmds.go
- pkg/cli/display/color.go
> keep args mapping order when mix-use like: `args.auto=arg1,arg2,*`

- pkg/cli/core/args.go
- pkg/cli/core/args_auto_map.go
- pkg/cli/core/cmd.go
- pkg/proto/mod_meta/mod_reg.go
All formats below are legal:
```
args.auto = auto-map-arg1, auto-map-arg2
```
```
args.auto = auto-map-arg1, auto-map-arg2, regular-arg = value, *
```
```
[args.auto/]
auto-map-arg1,
auto-map-arg2, auto-map-arg3
regular-arg = value
*
[/args.auto]
```
> allow args mapping in mix mode

- pkg/cli/core/args_auto_map.go
> fix bug: args re-order failed when args are not fully auto mapped

- pkg/builtin/builtin.go
- pkg/builtin/env.go
> `env.rm.prefix`: batchly delete key-values by prefix

- pkg/cli/core/args.go
> fix bug: args order not right when mixed using auto-map and normal args

- pkg/cli/display/flow.go
> fix bug: display subflows of a executed flow

- pkg/cli/execute/executor.go
- pkg/cli/execute/interactive.go
> use env to keep/pass the `break-at-next` breakpoint status flag
