pkg/builtin/dump_flow.go
pkg/builtin/hub.go
pkg/cli/display/dep.go
pkg/cli/display/suggest.go
pkg/main/main.go

fix bug: missed env cloning cause wrong flow desc

---

pkg/builtin/builtin.go
pkg/builtin/help.go
pkg/cli/display/cmds.go
pkg/cli/display/suggest.go

add command 'args' to display help and args

---

pkg/builtin/builtin.go
pkg/builtin/help.go
pkg/cli/display/cmds.go

better usage help provided by command 'args'

---

pkg/builtin/builtin.go
pkg/builtin/help.go
pkg/cli/display/suggest.go

re-arange help commands: $, =, ==, --

---

pkg/cli/display/args.go
pkg/cli/display/err.go
pkg/cli/display/flow.go

fix bug on flow desc: hide args when they are mapper and inactive

---

pkg/builtin/builtin.go
pkg/builtin/help.go
pkg/builtin/hub.go
pkg/builtin/mod.go
pkg/cli/core/cli.go
pkg/cli/core/cmds.go
pkg/cli/core/helps.go
pkg/cli/display/cmds.go
pkg/cli/display/help.go
pkg/cli/execute/cmd_type.go
pkg/cli/execute/executor.go
pkg/cli/parser/cmd_test.go
pkg/main/main.go
pkg/proto/mod_meta/mod_reg.go

add tags and help-file support

---

pkg/builtin/builtin.go
pkg/builtin/env.go
pkg/builtin/help.go
pkg/builtin/misc.go
pkg/cli/core/cmd.go
pkg/cli/core/errs.go
pkg/cli/display/args.go
pkg/cli/display/cmds.go
pkg/cli/display/color.go
pkg/cli/display/dep.go
pkg/cli/display/env.go
pkg/cli/display/env_ops.go
pkg/cli/display/err.go
pkg/cli/display/executor.go
pkg/cli/display/flow.go
pkg/cli/display/help.go
pkg/cli/display/parse_err.go
pkg/cli/display/render.go
pkg/cli/display/tip.go
pkg/cli/execute/cmd_type.go
pkg/proto/mod_meta/mod_reg.go
pkg/utils/misc.go

add color display support

---

pkg/builtin/builtin.go
pkg/cli/display/cmds.go
pkg/cli/display/color.go
pkg/cli/display/env_ops.go
pkg/cli/display/tip.go

add some display switching commands

---

pkg/builtin/builtin.go
pkg/builtin/dump_env.go
pkg/builtin/dump_flow.go
pkg/builtin/flow.go
pkg/builtin/help.go
pkg/builtin/hub.go
pkg/builtin/utils.go
pkg/cli/display/color.go
pkg/cli/display/suggest.go
pkg/cli/display/tip.go
pkg/cli/execute/executor.go

flow commands support tail-mode, and better display

---

doc/spec/mod-meta.md
pkg/builtin/dbg.go
pkg/builtin/display.go
pkg/builtin/dump_cmds.go
pkg/builtin/dump_env.go
pkg/builtin/dump_flow.go
pkg/builtin/env.go
pkg/builtin/flow.go
pkg/builtin/help.go
pkg/builtin/hub.go
pkg/builtin/misc.go
pkg/builtin/mod.go
pkg/builtin/utils.go
pkg/builtin/verb.go
pkg/cli/core/cmd.go
pkg/cli/core/parsing.go
pkg/cli/execute/executor.go
pkg/cli/parser/cmd_test.go

support recursive tail-mode

---

pkg/builtin/dump_flow.go
pkg/builtin/misc.go
pkg/cli/core/cli.go
pkg/cli/core/dep.go
pkg/cli/core/env_ops.go
pkg/cli/display/dep.go
pkg/cli/execute/executor.go

execute env-op cmds in flow desc, to get correct checking

---

pkg/cli/core/cmd.go
pkg/proto/meta_file/meta_file.go

support multi line flow defining in meta file

---

pkg/cli/core/cmd.go
pkg/cli/core/cmds.go
pkg/cli/display/cmds.go
pkg/cli/display/flow.go
pkg/proto/mod_meta/mod_reg.go

support both flow and executable definition in a same command

---

pkg/cli/display/flow.go
pkg/cli/parser/cmd.go

flow desc: do error check even the commands are folded by trivial level

---

pkg/builtin/builtin.go
pkg/cli/display/flow.go

flow desc: new display; fix auto-fold. add env-op-write to cmd mark-time

---

pkg/builtin/builtin.go
pkg/builtin/misc.go
pkg/builtin/utils.go
pkg/cli/display/flow.go

add timer.begin|elapsed commands

---

pkg/builtin/bg_tasks.go
pkg/builtin/builtin.go
pkg/cli/display/render.go
pkg/cli/execute/executor.go

add command 'bg.wait' to wait for all bg tasks to finish, can only use in main thread

---

pkg/builtin/builtin.go
pkg/builtin/env.go
pkg/cli/display/env.go

add command env.map src-key dest-key'

---

pkg/cli/core/flow.go

Fix bugs when saving a flow:
* has ':' in arg-val or env-val
* a cmd have both env-definition and arg-definition

fix bugs when saving a flow: has ':' in arg or env

---

pkg/builtin/builtin.go
pkg/builtin/flow.go
pkg/cli/core/env_ops.go
pkg/cli/display/cmds.go
pkg/cli/display/suggest.go

This command shows all commands which write the specified key

fix and improve cmd 'env.who-write'

---

pkg/builtin/bg_tasks.go
pkg/builtin/builtin.go
pkg/builtin/env.go
pkg/cli/core/cli.go
pkg/cli/core/cmd.go
pkg/cli/core/dep.go
pkg/cli/core/env.go
pkg/cli/core/env_ops.go
pkg/cli/display/suggest.go
pkg/cli/execute/executor.go
pkg/cli/parser/cmd.go
pkg/cli/parser/cmds.go
pkg/main/main.go

This is for make env has a corrent layer structure.

Refine env layers: remove cli.GlobalEnv, add EnvLayerSubFlow

---

pkg/builtin/builtin.go
pkg/builtin/env.go
pkg/builtin/sessions.go
pkg/cli/core/cmd.go
pkg/cli/core/executing.go
pkg/cli/core/session.go
pkg/cli/display/flow.go
pkg/cli/execute/executor.go

add env changes tracing display in executed flow desc

---

pkg/builtin/sessions.go
pkg/cli/display/flow.go

tidy code: flow desc

---

pkg/builtin/builtin.go
pkg/builtin/hub.go
pkg/proto/hub_meta/hub_repo.go

1)
Add cmd `hub.status` to check out the status of local fetched repos.
2)
Relocate storing path for each git repo.
The existed repos stored in local dirs will stay untouched(could remove by `hub.reset` or `hub.rm`),
`hub.init` or `hub.add` may needed for re-adding the old repos.

repo local dir: .../<project> => .../<author>/<project>

---

pkg/cli/core/bg_tasks.go
pkg/cli/core/cli.go
pkg/cli/core/cmd.go
pkg/cli/core/errs.go
pkg/cli/core/executed.go
pkg/cli/core/executing.go
pkg/cli/display/err.go
pkg/cli/display/flow.go
pkg/main/main.go
pkg/utils/misc.go

log cmd output and shows it in session desc if session failed

---

pkg/cli/display/flow.go

better display in session desc with depth mark

---

pkg/builtin/builtin.go
pkg/builtin/dbg.go
pkg/builtin/sessions.go
pkg/cli/core/breakpoints.go
pkg/cli/core/cli.go
pkg/cli/core/cmd.go
pkg/cli/display/flow.go
pkg/cli/execute/executor.go

support breakpoints by cmd 'dbg.break.at <cmd-list>'

---

pkg/cli/display/help.go
pkg/cli/display/suggest.go

colorize help-info

---

pkg/builtin/builtin.go
pkg/builtin/env.go

add commands: env.add, env.set, env.update

---

pkg/builtin/interactive.go
pkg/cli/core/cmds.go
pkg/cli/display/parse_err.go

better and faster completion in interact-mode

---

pkg/builtin/bg_tasks.go
pkg/builtin/builtin.go
pkg/builtin/interactive.go
pkg/cli/core/bg_tasks.go
pkg/cli/display/executor.go
pkg/cli/display/help.go
pkg/cli/execute/executor.go

handle bg task errors

---

pkg/builtin/builtin.go
pkg/builtin/env.go
pkg/builtin/interactive.go

support two styles of completion

---

CHANGELOG.md
pkg/builtin/builtin.go
pkg/builtin/hub.go
pkg/builtin/interactive.go
pkg/builtin/mod.go
pkg/builtin/tags.go
pkg/cli/core/cmds.go
pkg/cli/display/parse_err.go

reduce some abbrs, all capital abbrs are removed

---

CHANGELOG.md
pkg/builtin/interactive.go

better (still very bad) args completion in interact-mode

---

pkg/builtin/builtin.go
pkg/builtin/dbg.go

add command for ext-executor setting

---

pkg/cli/display/executor.go
pkg/cli/display/flow.go

fix display bugs: 1, args in desc session; 2, one-cmd subflow exec info

---

pkg/builtin/builtin.go
pkg/builtin/misc.go
pkg/cli/core/parsing.go
pkg/cli/execute/cmd_type.go
pkg/cli/execute/interactive.go

feature: selftest

---

pkg/builtin/builtin.go
pkg/builtin/env.go
pkg/builtin/sessions.go
pkg/utils/misc.go

add commands: list sessions by type

---

pkg/builtin/env.go
pkg/builtin/sessions.go
pkg/cli/display/flow.go

hide quiet commands in flow desc

---

pkg/cli/display/flow.go

display elapsed duration in session desc

---

pkg/builtin/display.go
pkg/builtin/env.go
pkg/cli/display/flow.go
pkg/cli/display/help.go
pkg/utils/misc.go

better display width

---

pkg/cli/display/flow.go
pkg/utils/misc.go

display more success cmds in flow when desc a running session

---

pkg/builtin/builtin.go
pkg/builtin/misc.go
pkg/builtin/sessions.go
pkg/cli/core/executed.go
pkg/cli/core/session.go
pkg/cli/display/flow.go

support parallel selftest

---

pkg/builtin/builtin.go
pkg/builtin/misc.go
pkg/cli/display/flow.go

move command to global: dbg.break.*, dbg.step, dbg.delay

---

pkg/builtin/api.go
pkg/builtin/builtin.go
pkg/builtin/env.go
pkg/builtin/sessions.go
pkg/cli/core/session.go
pkg/cli/display/flow.go
pkg/cli/execute/executor.go
pkg/utils/misc.go

add api command set; add session id and host ip to env

---

pkg/cli/core/cmd.go
pkg/cli/display/cmds.go
pkg/proto/mod_meta/mod_reg.go

support quiet-error flag in meta

---

pkg/builtin/builtin.go
pkg/builtin/join.go

implement join for ticat
example:
```bash
ticat join.new cmd "ls,du -sh" : join.run bash
```

feat: join

---

pkg/builtin/builtin.go
pkg/builtin/env.go
pkg/builtin/misc.go
pkg/builtin/utils.go
pkg/cli/core/blender.go
pkg/cli/core/cmd.go
pkg/cli/core/parsing.go
pkg/cli/display/parse_err.go
pkg/cli/display/suggest.go
pkg/cli/execute/cmd_type.go
pkg/cli/execute/executor.go

Plus: change default repo from innerr/marsh to ticat-mods/marsh

fix: incorrect error messages when using tail-mode and tail-mode call

---

pkg/builtin/env.go

change default repo from innerr/marsh.ticat to ticat-mods/marsh

---

pkg/cli/display/err.go
pkg/cli/display/flow.go

not show log-file when it's empty in error box; keep args order in desc

---

pkg/builtin/builtin.go
pkg/builtin/env.go
pkg/builtin/misc.go
pkg/cli/core/cli.go
pkg/cli/core/cmd.go
pkg/cli/core/cmds.go
pkg/cli/core/executed.go
pkg/cli/core/parsing.go
pkg/cli/core/proto.go
pkg/cli/display/executor.go
pkg/cli/execute/executor.go
pkg/proto/meta_file/meta_file.go

fix some small bugs

---

pkg/builtin/env.go
pkg/cli/core/proto.go

add env: display.width.max

---

pkg/builtin/env.go
pkg/cli/core/cmds.go
pkg/cli/parser/env.go
pkg/cli/parser/env_test.go
pkg/cli/parser/sequence.go

fix bug: when empty arg in the midle of args list, args are wrong

---

pkg/builtin/builtin.go
pkg/builtin/misc.go

feature repeat: run a command many times

---

pkg/builtin/env.go
pkg/cli/core/env_mapper.go

better display in mod-loading error

---

pkg/cli/display/err.go
pkg/cli/execute/cmd_type.go

fix bug in tail-mode-call with parse error

---

pkg/builtin/dump_cmd.go
pkg/builtin/help.go
pkg/cli/display/err.go

fix 'dump cmd' and 'tail cmds' bugs in tail-mode call

---

pkg/builtin/dump_flow.go

fix dump flow commands' bug when flow has parse errors

---

pkg/builtin/builtin.go
pkg/builtin/sessions.go
pkg/cli/core/cli.go
pkg/cli/core/session.go
pkg/cli/execute/cmd_type.go

better sessions command set, to avoid id copying in use

---

CHANGELOG.md
pkg/builtin/builtin.go
pkg/builtin/env.go

bump v1.2.1

---

pkg/builtin/join.go

implement join range for ticat
example:
```bash
ticat join.new msg "[1,5,2]" : join.run echo
ticat join.new msg "[1,5]" : join.run echo
```
equivalent to:
```
ticat join.new msg "1,3,5" : join.run echo
ticat join.new msg "1,2,3,4,5" : join.run echo
```

feat: join range

---

pkg/cli/core/dep.go
pkg/cli/core/env_ops.go

fix subflow checking in ad-hot flow

---

CHANGELOG.md
pkg/builtin/env.go

update change log for 1.3.0

---

pkg/builtin/builtin.go
pkg/builtin/sessions.go
pkg/cli/core/argv.go
pkg/cli/display/flow.go

cmd `session.running.desc.monitor`, for display running status

---

pkg/builtin/builtin.go
pkg/builtin/sessions.go
pkg/cli/display/flow.go

new cmd `session.monitor`; better monitor display

---

pkg/builtin/interactive.go
pkg/builtin/sessions.go
pkg/cli/display/flow.go
pkg/cli/execute/executor.go
pkg/cli/execute/interactive.go

filtered `done` sessions in monitoring, better display

---

pkg/builtin/builtin.go
pkg/cli/display/flow.go
pkg/main/main.go

`hook.exit/error/done`: hook a flow to events

---

pkg/cli/core/env.go
pkg/cli/display/color.go
pkg/cli/display/frame.go
pkg/cli/display/screen.go
pkg/cli/display/tip.go

use dark mode to display tip messages and frame

---

pkg/builtin/builtin.go
pkg/builtin/env.go
pkg/cli/display/color.go
pkg/cli/display/flow.go
pkg/cli/display/tip.go
pkg/main/main.go

some display optimizations, include using red error tip-box frame

---

pkg/proto/mod_meta/mod_reg.go

support `quiet=true` in meta file

---

pkg/builtin/builtin.go
pkg/builtin/sessions.go
pkg/cli/core/cmd.go
pkg/proto/mod_meta/mod_reg.go

support `hide-in-sessions-last` flag in meta file

---

pkg/cli/core/cli.go
pkg/cli/core/executed.go
pkg/cli/display/executor.go
pkg/cli/execute/executor.go

display executed status for session retry, useful for review

---

pkg/builtin/env.go
pkg/cli/core/cli.go
pkg/cli/core/cmd.go
pkg/cli/core/executed.go
pkg/cli/display/executor.go

fix bug: in session retry, succeeded file-n-flow cmd wrongly re-execute

---

pkg/cli/core/cmd.go
pkg/cli/execute/executor.go

fix bugs about re-run and re-re-run

---

pkg/builtin/builtin.go
pkg/builtin/dbg.go
pkg/builtin/env.go
pkg/builtin/flow.go
pkg/cli/core/proto.go
pkg/cli/display/executor.go
pkg/cli/execute/executor.go
pkg/cli/execute/interactive.go

fix bug: not persist break point status

---

pkg/builtin/builtin.go
pkg/builtin/env.go
pkg/cli/core/args_auto_map.go
pkg/cli/core/cmd.go
pkg/cli/display/cmds.go
pkg/cli/display/color.go
pkg/cli/display/flow.go

display args auto mapping info in `cmd`

---

pkg/builtin/api.go
pkg/builtin/builtin.go
pkg/cli/core/args_auto_map.go
pkg/cli/core/cmds.go
pkg/cli/display/cmds.go

api cmd: `api.cmd.list.all`

---

pkg/cli/core/cmd.go
pkg/cli/execute/executor.go
pkg/cli/execute/interactive.go

fix bug: FileNFile cmd not puase during step-by-step

---

pkg/cli/execute/interactive.go

fix bug: step out a subflow but did not pause as expected

---

pkg/cli/core/cmd.go
pkg/cli/display/executor.go
pkg/cli/execute/executor.go
pkg/cli/execute/interactive.go

fix bug: when retry a skipped subflow, step-in option is showed

---

pkg/builtin/builtin.go
pkg/builtin/env.go
pkg/cli/display/args.go
pkg/cli/display/cmds.go
pkg/cli/display/env.go
pkg/cli/display/flow.go
pkg/cli/display/utils.go

add a switch for display sensitive env values or args

---

pkg/builtin/builtin.go
pkg/cli/core/cli.go
pkg/cli/display/flow.go

enable blender cmds: `flow.replace*`

---

pkg/cli/core/args.go
pkg/cli/core/args_auto_map.go
pkg/cli/core/blender.go
pkg/cli/core/cmd.go
pkg/cli/core/dep.go
pkg/cli/core/env.go
pkg/cli/core/env_ops.go
pkg/cli/core/parsing.go
pkg/cli/display/args.go
pkg/cli/display/cmds.go
pkg/cli/display/executor.go
pkg/cli/display/flow.go
pkg/cli/execute/executor.go

not use def-val for auto-map-all args inside flows

---

pkg/cli/core/cmd.go
pkg/cli/core/env_ops.go
pkg/cli/core/session.go
pkg/cli/display/executor.go
pkg/cli/execute/executor.go
pkg/proto/mod_meta/mod_reg.go

support `quiet-subflow` flag in meta file

---

pkg/cli/core/cmd.go
pkg/proto/mod_meta/mod_reg.go

apply quiet-subflow feature to all types of flow cmds

---

pkg/cli/core/template.go
pkg/main/main.go

support sys var `RANDOM` in template

---

pkg/builtin/builtin.go
pkg/builtin/dbg.go
pkg/cli/display/color.go
pkg/cli/execute/cmd_type.go

support color in cmd `echo`; new cmd `echo.ln`

---

pkg/cli/core/args_auto_map.go
pkg/cli/core/cmd.go
pkg/cli/core/dep.go
pkg/cli/core/env_ops.go
pkg/cli/display/cmds.go
pkg/cli/display/executor.go
pkg/cli/display/flow.go
pkg/cli/execute/interactive.go
pkg/proto/mod_meta/mod_reg.go

support `pack-subflow` in meta file, to totally hide suflow

---

CHANGELOG.md
pkg/builtin/env.go
pkg/cli/core/proto.go
pkg/cli/display/tip.go

fix tip frame display under no-color mode

---

pkg/builtin/bg_tasks.go
pkg/cli/core/proto.go
pkg/cli/display/executor.go
pkg/cli/display/flow.go
pkg/cli/display/render.go
pkg/cli/execute/executor.go
pkg/cli/parser/cmds.go

display: better wording; fix fake issue #227

---

CHANGELOG.md

change log of v1.4.0

---

pkg/builtin/sessions.go
pkg/cli/core/executed.go
pkg/cli/core/session.go
pkg/cli/display/color.go
pkg/cli/display/flow.go

display: fix and improve finish-ts display when session failed/running

---

pkg/builtin/sessions.go
pkg/cli/display/flow.go

display: fix session running elapsed time display

---

pkg/builtin/builtin.go
pkg/builtin/flow.go
pkg/proto/flow_file/flow_file.go

add more args to `flow.save`

---

pkg/builtin/flow.go

support abbrs in `flow.*`, resolve cmd name conflictions

---

pkg/cli/parser/cmd.go
pkg/cli/parser/cmd_test.go
pkg/main/main.go

fix bug: ticat cmd arg-start-with-dot

---

pkg/builtin/builtin.go
pkg/builtin/flow.go
pkg/builtin/hub.go
pkg/builtin/utils.go
pkg/cli/core/argv.go
pkg/utils/misc.go

better flow moving cmds `flow.mv.all.*`

---

pkg/cli/core/cmd.go

support flag `no-session` in meta file

---

pkg/builtin/builtin.go
pkg/builtin/hub.go
pkg/proto/flow_file/flow_file.go

better args for `hub.add.*`

---

pkg/builtin/builtin.go
pkg/builtin/hub.go
pkg/cli/core/argv.go
pkg/main/main.go

trigger `hub.init` at the first time running

---

pkg/builtin/builtin.go
pkg/builtin/flow.go
pkg/proto/flow_file/flow_file.go
pkg/proto/mod_meta/mod_reg.go

add arg `pack-subflow` for cmd `flow.save`

---

pkg/builtin/hub.go

after adding a repo to hub, load cmds from it

---

pkg/builtin/builtin.go
pkg/cli/core/args.go
pkg/cli/core/cmd.go
pkg/cli/core/cmds.go
pkg/cli/display/cmds.go
pkg/main/main.go
pkg/proto/mod_meta/mod_reg.go

support arg enum list
